# Lecture 3 – Python Basics

In [1]:
# Imports
import pandas as pd
import numpy as np

import plotly.express as px
import matplotlib.pyplot as plt
plt.style.use('ggplot')

## Demo

### The *Federalist Papers* (1787–88)

- Hamilton, Madison, and Jay wrote 85 essays under one pen name, *Publius*, to argue for the new Constitution.
    - For 11 of them, historians long disagreed about whether Hamilton or Madison was the author.
- Using tools from this class, we'll look for each author's writing habits, without reading all 85 essays.
- Do not worry about any of this code – we'll cover the necessary pieces in the weeks to come. Sit back and relax!

In [2]:
# Read in essay 10 (by Madison) to a variable called essay_10.
# The course data live two folders up, in data/raw/.
essay_10 = open('../../data/raw/federalist/fp10.txt', encoding='utf-8').read()

In [3]:
# See the first thousand characters.
essay_10[:1000]

'AMONG the numerous advantages promised by a well-constructed Union, none \n        deserves to be more accurately developed than its tendency to break and \n        control the violence of faction. The friend of popular governments never \n        finds himself so much alarmed for their character and fate, as when he \n        contemplates their propensity to this dangerous vice. He will not fail, \n        therefore, to set a due value on any plan which, without violating the \n        principles to which he is attached, provides a proper cure for it. The \n        instability, injustice, and confusion introduced into the public councils, \n        have, in truth, been the mortal diseases under which popular governments \n        have everywhere perished; as they continue to be the favorite and fruitful \n        topics from which the adversaries to liberty derive their most specious \n        declamations. The valuable improvements made by the American constitutions \n        on the popular mode'

In [4]:
# Print the first thousand characters.
print(essay_10[:1000])

AMONG the numerous advantages promised by a well-constructed Union, none
        deserves to be more accurately developed than its tendency to break and
        control the violence of faction. The friend of popular governments never
        finds himself so much alarmed for their character and fate, as when he
        contemplates their propensity to this dangerous vice. He will not fail,
        therefore, to set a due value on any plan which, without violating the
        principles to which he is attached, provides a proper cure for it. The
        instability, injustice, and confusion introduced into the public councils,
        have, in truth, been the mortal diseases under which popular governments
        have everywhere perished; as they continue to be the favorite and fruitful
        topics from which the adversaries to liberty derive their most specious
        declamations. The valuable improvements made by the American constitutions
        on the popular mode

In [5]:
# Read all 85 essays into a list called essays, in order.
from glob import glob
files = sorted(glob('../../data/raw/federalist/fp*.txt'))
essays = [open(f, encoding='utf-8').read().lower() for f in files]

# Create a DataFrame with one column - the text of each essay.
pd.DataFrame().assign(essay=essays)

                                                essay
0   after an unequivocal experience of the ineffic...
1   when the people of america reflect that they a...
2   it is not a new observation that the people of...
3   my last paper assigned several reasons why the...
4   queen anne, in her letter of the 1st july, 170...
..                                                ...
80  let us now return to the partition of the judi...
81  the erection of a new government, whatever car...
82  the objection to the plan of the convention, w...
83  in the course of the foregoing review of the c...
84  according to the formal division of the subjec...

[85 rows x 1 columns]

In [6]:
# Number of occurrences of a few small words in each essay.
# Authors do not think about these words, which is what makes them habits.

counts = pd.DataFrame().assign(
    upon=np.char.count(essays, ' upon '),
    whilst=np.char.count(essays, ' whilst '),
    while_=np.char.count(essays, ' while '),   # 'while' is a Python keyword, so add _
    by=np.char.count(essays, ' by '),
)
counts

    upon  whilst  while_  by
0      6       0       0  14
1      1       0       1  10
2      0       0       0  18
3      0       0       0  14
4      0       0       0  10
..   ...     ...     ...  ..
80    13       1       2  31
81     4       0       0   4
82    20       0       4  79
83    10       0       1  28
84    11       0       0  11

[85 rows x 4 columns]

In [7]:
# Cumulative number of times each word appears, essay by essay.

cumulative_counts = pd.DataFrame().assign(
    upon=np.cumsum(counts.get('upon')),
    whilst=np.cumsum(counts.get('whilst')),
    while_=np.cumsum(counts.get('while_')),
    by=np.cumsum(counts.get('by')),
    Essay=np.arange(1, 86, 1)
)

cumulative_counts

    upon  whilst  while_    by  Essay
0      6       0       0    14      1
1      7       0       1    24      2
2      7       0       1    42      3
3      7       0       1    56      4
4      7       0       1    66      5
..   ...     ...     ...   ...    ...
80   332      24      32  1603     81
81   336      24      32  1607     82
82   356      24      36  1686     83
83   366      24      37  1714     84
84   377      24      37  1725     85

[85 rows x 5 columns]

In [8]:
df = cumulative_counts.drop(columns=['Essay']).melt().rename(columns={'variable': 'word', 'value': 'Count'})
df.assign(Essay=list(range(1, 86)) * 4)

     word  Count  Essay
0    upon      6      1
1    upon      7      2
2    upon      7      3
3    upon      7      4
4    upon      7      5
..    ...    ...    ...
335    by   1603     81
336    by   1607     82
337    by   1686     83
338    by   1714     84
339    by   1725     85

[340 rows x 3 columns]

In [9]:
# Putting it all together, we get a helpful visualization.
# Hamilton wrote most of essays 1-36 and 59-85; Madison wrote most of 37-58.
cumulative_counts_df = cumulative_counts.drop(columns=['Essay']).melt().rename(columns={'variable': 'word', 'value': 'Count'})
cumulative_counts_df = cumulative_counts_df.assign(Essay=list(range(1, 86)) * 4)
px.line(cumulative_counts_df, x='Essay', y='Count', color='word', width=900, height=600, title='Cumulative Number of Times Each Word Appears', template='ggplot2').show()

### Jupyter Notebooks 📓

- Often, code is written in a text editor and then run in a command-line interface (or both steps are done in an IDE).

<center>
<img src='images/terminal.png' width=800>
</center>

- **Jupyter Notebooks** allow us to write and run code within a single document. They also allow us to embed text (in Markdown format) and code.

## Expressions

- An **expression** is a combination of values, operators, and functions that **evaluates** to some **value**.

- For now, let's think of Python like a calculator – it takes expressions and evaluates them.

- We will enter our expressions in **code cells**. To run a code cell, either:
    - **Hit `shift` + `enter` (or `shift` + `return`) on your keyboard (strongly preferred)**, or
    - Press the "▶ Run" button in the toolbar.

In [ ]:
23

In [ ]:
-15 + 2.718

In [ ]:
4 ** 3

In [ ]:
(2 + 3 + 4) / 3

In [ ]:
# Only one value is displayed. Why?
9 + 10
13 / 4
21

### Arithmetic operations

| Operation | Operator | Example | Value | 
| --- | --- | --- | --- |
| Addition | `+` | `2 + 3` | `5` |
| Subtraction | `-` | `2 - 3` | `-1` |
| Multiplication | `*` | `2 * 3` | `6` |
| Division | `/` | `7 / 3` | `2.66667` |
| Remainder | `%` | `7 % 3` | `1` |
| Exponentiation | `**` | `2 ** 0.5` | `1.41421` |

### Python uses the typical order of operations – PEMDAS

- P arentheses (and other grouping symbols)
- E xponents
- MD Multiplication and Division
- AS Addition and Subtraction

In [ ]:
5 * 2 ** 3

In [ ]:
(5 * 2) ** 3

## Variables

### Motivation

Below, we compute the number of seconds in a year.

In [ ]:
60 * 60 * 24 * 365

If we want to use the above value later in our notebook to find, say, the number of seconds in 12 years, we'd have to copy-and-paste the expression. **This is inconvenient, and prone to introducing errors.**

In [ ]:
60 * 60 * 24 * 365 * 12

It would be great if we could **store** the initial value and refer to it later on!

### Variables and assignment statements

- A **variable** is a place to store a value so that it can be referred to later in our code. To define a variable, we use an **assignment statement**.

$$ \overbrace{\texttt{zebra}}^{\text{name}} = \overbrace{\texttt{23 - 14}}^{\text{any expression}} $$

-  An assignment statement changes the meaning of the **name** to the left of the `=` symbol.

- The expression on the right-hand side of the `=` symbol is evaluated before being assigned to the name on the left-hand side.
    * e.g. `zebra` is bound to `9` (value) not `23 - 14` (expression).

### Think of variable names as nametags!

In [ ]:
# Note: This is an assignment statement, not an expression.
# Assignment statements don't output anything!
a = 1

In [ ]:
a = 2

In [ ]:
b = 2

### Naming variables

- Give your variables helpful names so that you know what they refer to.
- Variable names can contain uppercase and lowercase characters, the digits 0-9, and underscores.
    - They cannot start with a number.
    - They are case sensitive!

The following assignment statements are **valid**, but use **poor** variable names 😕.

In [ ]:
six = 15

In [ ]:
i_45love_chocolate_9999 = 60 * 60 * 24 * 365

The following assignment statements are **valid**, and use **good** variable names ✅.

In [ ]:
seconds_per_hour = 60 * 60
hours_per_year = 24 * 365
seconds_per_year = seconds_per_hour * hours_per_year

### Python functions

- Functions in Python work the same way functions in math do.
- The inputs to functions are called **arguments**.
- Python comes with a number of built-in functions that we are free to use.
- **Calling** a function, or using a function, means asking the function to "run its recipe" on the given input.

In [ ]:
abs(-23)

### Some functions can take a variable number of arguments

In [ ]:
max(4, -8)

In [ ]:
max(2, -3, -6, 10, -4)

In [ ]:
max(9)

In [ ]:
max(9 + 10, 9 - 10)

### Put ```?``` after a function's name to see its documentation 📄

Or use the `help` function, e.g. `help(round)`.

In [ ]:
round(1.45678)

In [ ]:
round?

In [ ]:
round(1.45678, 3)

### Nested evaluation

We can **nest** many function calls to evaluate sophisticated expressions.

In [ ]:
min(abs(max(-1, -2, -3, min(4, -2))), max(5, 100))

### Import statements
- Python doesn't have everything we need built in.
- In order to gain additional functionality, we import **modules** through **import statements**.
- **Modules** are collections of Python functions and values.
- Call these functions using the syntax `module.function()`, called "dot notation".

### Example: `import math`

Some of the many functions built into the `math` module are `sqrt`, `pow`, and `log`.

In [ ]:
import math

In [ ]:
math.sqrt(16)

In [ ]:
math.pow(2, 5)

`math` also has constants built in!

In [ ]:
math.pi

## Data types

### What's the difference? 🧐

In [ ]:
4 / 2

In [ ]:
5 - 3

To us, `2.0` and `2` are the same number, $2$. But to Python, these appear to be different!

### Data types
- Every value in Python has a **type**.
    - Use the `type` function to check a value's type.
- It's important to understand how different types work with different operations, as the results may not always be what we expect.

### Two numeric data types: ```int``` and ```float``` 
- ```int```: An integer of any size.
- ```float```: A number with a decimal point.

### ```int```
- If you add (`+`), subtract (`-`), multiply (`*`), or exponentiate (`**`) `int`s, the result will be another `int`.
- `int`s have arbitrary precision in Python, meaning that your calculations will always be exact.

In [ ]:
7 - 15

In [ ]:
type(7 - 15)

In [ ]:
2 ** 300

In [ ]:
2 ** 3000

### ```float```
* A `float` is specified using a **decimal** point.
* A `float` might be printed using scientific notation.

In [ ]:
3.2 + 2.5

In [ ]:
type(3.2 + 2.5)

In [ ]:
# The result is in scientific notation: e+90 means "times 10^90".
2.0 ** 300

### The pitfalls of ```float```
* `floats` have limited precision; after arithmetic, the final few decimal places can be wrong in unexpected ways.
* `float`s have limited size, though the limit is huge.

In [ ]:
1 + 0.2

In [ ]:
1 + 0.1 + 0.1

In [ ]:
2.0 ** 3000

### Converting between ```int``` and ```float```
- If you mix `int`s and `float`s in an expression, the result will always be a `float`.
     - Note that when you divide two `int`s, you get a `float` back.
- A value can be explicity **coerced** (i.e. converted) using the ```int``` and ```float``` functions.

In [ ]:
2.0 + 3

In [ ]:
12 / 2

In [ ]:
int(12 / 2)

In [ ]:
int(-2.9)

### Summary

- Expressions evaluate to values. Python will display the value of the last expression in a cell by default.
- Python knows about all of the standard mathematical operators and follows PEMDAS.
- Assignment statements allow us to bind values to variables.
- We can call functions in Python similar to how we call functions in math.
    - Python knows some functions by default, and import statements allow us to bring additional functionality from modules.
- All values in Python have a data type.
    - `int`s and `float`s are numbers.
    - `int`s are integers, while `float`s contain decimal points.

## Strings

### Strings 

- A string is a snippet of text of any length.
- In Python, strings are enclosed by either single quotes or double quotes (doesn't matter which!)

In [ ]:
'woof'

In [ ]:
type('woof')

In [ ]:
"woof   🐶🐶"

In [ ]:
# A string, not an int!
"1998" + "45"

### String arithmetic

When using the `+` symbol between two strings, the operation is called "concatenation".

In [ ]:
s1 = 'baby'
s2 = '🐼'

In [ ]:
s1 + s2

In [ ]:
s1 + ' ' + s2

In [ ]:
s1 * 3 # multiplication is repeated addition, same as s1 + s1 + s1

### String methods
* Associated with strings are special functions, called **string methods**.
* Access string methods with a `.` after the string ("dot notation").    
    * For instance, to use the `upper` method on string `s`, we write `s.upper()`.
* Examples include `upper`, `title`, and `replace`, but there are [many more](https://docs.python.org/3/library/stdtypes.html#string-methods).

In [ ]:
my_cool_string = 'data science is super cool!'

In [ ]:
my_cool_string.title()

In [ ]:
my_cool_string.upper()

In [ ]:
my_cool_string.replace('super cool', '💯' * 3)

In [ ]:
"hello".upper()

In [ ]:
# len is not a method, since it doesn't use dot notation.
len(my_cool_string)

# Lists

## What is a list?

A list is an ordered sequence of values

A list of integers:
- [3, 1, 4, 1, 5, 9]

A list of strings:
- ["Once", "upon", "a", "time", "there"]


Each value has an index
- for [3, 1, 4, 1, 5, 9]

| Index| 0 | 1 | 2| 3 | 4 | 5 |
| ----- | - | - | - | - | - | - |
| List Entry  | 3 | 1 | 4 | 1 | 5 | 9 |


Indexing is zero-based (counting starts with zero):

## Loop Examples

[see in python tutor](https://tinyurl.com/y6a34bpd)

In [ ]:
for num in [2, 4, 6]:
    print(num)

In [ ]:
for i in [1, 2, 3]:
    print("Hi there!")

In [ ]:
for char in "happy": #sequence is a string, NOT a list
    print(char)      #prints the values of sequence

## The range function

A typical for loop does not use an explicit list:

In the following,
```
for i in range(5):
  … body
```
range(5) produced the numbers in the sequence [0, 1, 2, 3, 4]
 - note that range(5) __is not__ the same as the list [0, 1 ,2, 3, 4]
 - list(range(5)) is equivalent to the list [0, 1, 2, 3, 4]



__Detailed usage (1, 2, or 3 arguments)__

- range(5): cycles through [0, 1, 2, 3, 4] -> __Upper limit (exclusive)__

- range(1, 5): cycles through [1, 2, 3, 4] -> __Lower limit (inclusive)__

- range(1, 10, 2): cycles through [1, 3, 5, 7, 9] -> __step (distance between elements)__

In [ ]:
# Getting length of a list
print(len([3,1,4,1,5,9]))

## List Operations

What operations should a list support efficiently and conveniently?
- Creation
- Querying
- Modification

## List Creation
- run the following cells from __top to bottom__
- [see in python tutor](https://tinyurl.com/thb52x)

In [ ]:
a = [3, 1, 2 * 2, 1, 10 / 2, 10 - 1]
print(a)

In [ ]:
b = [5, 3, 'hi']
print(b)

In [ ]:
c = [4, 'a', a]
print(c)

In [ ]:
d = [[1, 2], [3, 4], [5, 6]]
print(d)

## List Querying

Expressions that return parts of lists:


Single element:  		__mylist[index]__

- The single element stored at that location

In [ ]:
l = [3,1,4,1,5,9]
print(l[2])

Sublist (“slicing”):  	__mylist[start:end]__

- the sublist that starts at *start*

- index start and ends at index *end – 1*

- If start is omitted: defaults to 0

- If end is omitted: defaults to len(mylist)

- mylist[:] and mylist[0:len(mylist)] both evaluate to the whole list

In [ ]:
a = [0, 1, 2, 3, 4]
print(a[0])

In [ ]:
a = [0, 1, 2, 3, 4]
print(a[5])

In [ ]:
a = [0, 1, 2, 3, 4]
print(a[6])

In [ ]:
a = [0, 1, 2, 3, 4]
print(a[-1]) # last element in list

In [ ]:
a = [0, 1, 2, 3, 4]
print(a[-2]) # next to last element

In [ ]:
a = [0, 1, 2, 3, 4]
print(a[0:2])

In [ ]:
a = [0, 1, 2, 3, 4]
print(a[0:-1])

## List Modification
- Insertion
- Removal
- Replacement
- Rearrangement

### List insertions
mylist.append(x)

- Extend mylist by inserting x at the end

mylist.extend(L)
- Extend mylist by appending all the items in the argument list L to the end of mylist

ylist.insert(i, x)
- Insert item x before position i.

a.insert(0, x)
- inserts at the front of the list

a.insert(len(a), x)
- is equivalent to    a.append(x)

In [ ]:
lst = [1, 2, 3, 4]
lst.append(5)
print(lst)

In [ ]:
lst = [1, 2, 3, 4]
lst.extend([6, 7, 8])
print(lst)

In [ ]:
lst = [1, 2, 3, 4]
lst.insert(3, 3.5)
print(lst)

__Comprehension check__

Which of the following is printed by the code below

- A) 4
- B) 5
- C) 2
- D) [4, 6]
- E) IndexError: list index out of range


```
lst = [1, 3, 5]
lst.insert(2, [4, 6])
print(lst[2])
```

In [ ]:
lst = [1, 3, 5]
lst.insert(2, [4, 6])
print(lst[2])

### List removal

mylist.remove(x)
- Remove the first item from the list whose value is x
- It is an error if there is no such item
- __Returns None__



mylist.pop([i])
- Remove the item at the given position in the list, and return it.
- If no index is given, mylist.pop() removes and returns the last item in the list.
- Notation from the Python Library Reference: *The square brackets around the parameter, “[i]”, means the argument is optional.
It does not mean you should type square brackets at that position.*

In [ ]:
#Examples
lst = [1, 2, 3, 4, 5, 6, 7]
print(lst.pop())

In [ ]:
lst = [1, 2, 3, 4, 5, 6, 7]
print(lst.pop(1))

In [ ]:
lst = [1, 2, 3, 4, 5, 6, 7]
print(lst.remove(3))

In [ ]:
lst = [1, 2, 3, 4, 5, 6, 7]
lst.remove(3)
print(lst)

### List replacement


```
mylist[index] = new_value
mylist[start:end] = new_sublist
```
Replaces mylist[start]  to   mylist[end – 1] with new_sublist


Can change the length of the list

Examples:
```
mylist[start:end] = []
```
removes mylist[start]… mylist[end – 1]
```
mylist[len(mylist):] = L
```
is equivalent to a.extend(L)

In [ ]:
#Examples
lst = [1, 2, 3, 4, 5, 6, 7]
lst[3] = 'blue'
print(lst)

In [ ]:
lst = [1, 2, 3, 4, 5, 6, 7]
lst[1:3] = [10, 11, 12]
print(lst)

### List Rearrangement

mylist.sort()
- Sort the items of the list, in place.
- “in place” means by modifying the original list,
not by creating a new list.

mylist.reverse()
- Reverse the elements of the list, in place.

both sort() and reverse() __return none__

In [ ]:
#Example
lst = [1, 2, 3, 4, 5, 6, 7]
lst.reverse()
print(lst)
lst.sort()
print(lst)

### List modification examples

- [see in python tutor](https://tinyurl.com/z2ktkhf2)

In [ ]:
lst = [10, 12, 23, 54, 15]
lst.append(7)
lst.extend([8, 9, 3])
lst.insert(2, 2.75)
lst.remove(3)
print(lst.pop())
print(lst.pop(4))
lst[1:5] = [20, 21, 22]
lst2 = [4, 6, 8, 2, 0]
lst2.sort()
lst2.reverse()
lst3 = lst2
lst4 = lst2[:]
lst2[-1]= 17

print(lst)
print(lst2)
print(lst3)
print(lst4)

## List operations comprehension check

1. What will convert list a into [1, 2, 3, 4, 5]

a = [1, 3, 5]

- A. a.insert(1, 2)

    a.insert(2, 4)
- B. a[1:2] = [2, 3, 4]
- C. a.extend([2, 4])
- D. a[1] = 2

     a[3] = 4

## Excercise: List lookup

Goal: implement the following ([see in python tutor](https://tinyurl.com/5dme2skr))

```
def my_index(lst, value):
  """Return the position of the first occurrence
  of value in the list lst. Return None if value
  does not appear in lst."""
```

Examples:

story = ["Once", "upon", "a", "time", "there", "was", "a"]

my_index(story, "a") → 2

my_index(story, "there") → 4

__Note__ :  my_list[my_index(my_list, x)] == x

In [ ]:
def my_index(lst, value):
  """Return the position of the first
  occurrence of value in the list lst.
  Return None if value does not appear
  in lst."""

## Exercise:  Convert Units

([see in python tutor](https://tinyurl.com/rccvsf49))

Using the following:

```
def cent_to_fahr(cent):
  return cent / 5.0 * 9 + 32

ctemps = [-40, 0, 20, 37, 100]

ftemps = []
```
Without setting it directly, set ftemps to [-40, 32, 68, 98.6, 212]

## More on list slicing

mylist[startindex:endindex] evaluates to a sublist of the original list
    
  - mylist[index] evaluates to an element of the original list

- Arguments are like those to the range function
mylist[start:end:step]
  - start index is inclusive, end index is exclusive
  - All 3 indices are optional
  - Can assign to a slice:  mylist[s:e] = yourlist

Example ([see in python tutor](https://tinyurl.com/y2cvczn6)):

In [ ]:
test_list = ['e0', 'e1', 'e2', 'e3', 'e4', 'e5', 'e6']
my_list = test_list[2:]
print(my_list)

In [ ]:
test_list = ['e0', 'e1', 'e2', 'e3', 'e4', 'e5', 'e6']
my_list = test_list[:5]
print(my_list)

In [ ]:
test_list = ['e0', 'e1', 'e2', 'e3', 'e4', 'e5', 'e6']
my_list = test_list[-1]
print(my_list)

In [ ]:
test_list = ['e0', 'e1', 'e2', 'e3', 'e4', 'e5', 'e6']
my_list = test_list[-4:]
print(my_list)

In [ ]:
test_list = ['e0', 'e1', 'e2', 'e3', 'e4', 'e5', 'e6']
my_list = test_list[:-3]
print(my_list)

In [ ]:
test_list = ['e0', 'e1', 'e2', 'e3', 'e4', 'e5', 'e6']
my_list = test_list[:]
print(my_list)

In [ ]:
test_list = ['e0', 'e1', 'e2', 'e3', 'e4', 'e5', 'e6']
my_list = test_list[::-1]
print(my_list)

__Answer__

test_list[2:]		From e2 to the end of the list

test_list[:5]		From beginning up to (but not including) e5

test_list[-1]		Last element

test_list[-4:]	    Last four elements

test_list[:-3]	    Everything except last three elements

test_list[:]		    Get a copy of the whole list

test_list[::-1]	    Reverse the list

## How to evaluate a list expression

There are two new forms of expression:
- List creation (aka, list literals):   [1, 2, 3, 4]
- List indexing (aka, dereferencing): a[i]

__Note:__ In the previous examples, there are the same tokens “[]” with two distinct meanings

## Evaluating list expressions

[a, b, c, d]		list __creation__
  - To evaluate:
    - evaluate each element to a value, from left to right
    - make a list of the values
  -The elements can be arbitrary values, including lists:
    - ["a", 3, fahr_to_cent(-40), [3 + 4, 5 * 6]]

a[b] 		list __indexing__

a is the list expression, b is the index

- To evaluate:
  - evaluate the list expression to a value
  - evaluate the index expression to a value
  - if the list value is not a list, execution terminates with an error
  - if the element is not in range (not a valid index), execution terminates with an error
  - the value is the given element of the list value (counting from zero)

### List expression examples

What does this mean (or is it an error)? ([see in python tutor](https://tinyurl.com/y5sg98eo))

In [ ]:
["Once", "upon", "a", "time", "there"][2]

In [ ]:
["Once", "upon", "a", "time", "there"][0,2,3]

In [ ]:
["Once", "upon", "a", "time", "there"][[0,2,3]]

In [ ]:
["Once", "upon", "a", "time", "there"][[0,2,3][1]]

## Two dimensional nested lists

Each single element within mylist is __also a list__.

(Remember: a list can contain just about anything.)

In [ ]:
mylist = [
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
]

mylist[0] evaluates to a list

In [ ]:
mylist = [
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
]
mylist[0]

mylist[0] is an expression that evaluates to the first item in mylist. This just happens to also be another list expression

mylist[0][0] evaluates to the first element of the first list in the nested list

In [ ]:
mylist = [
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
]
mylist[0][0]

Note the double square brackets below. Adding a list within a list within a list.

> Add blockquote

In [ ]:
mylist = [
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
]
mylist.append([[10,11,12]])
print(mylist)

Recall that items within a list don't have to all be the same type. What will the following do?

In [ ]:
mylist[0][0][0]

# Dictionaries

**Dictionaries** are a data structure that allows us to map **keys** to **values**. This is incredibly helpful! However there are some considerations that we must have when using **dictionaries**. We will see these in examples below!

Dictionaries map **keys** to **values**. Lets take a look at this

In [ ]:
value1 = 1
value2 = 2
value3 = 3
value4 = 4

# Lets create a dictionary
my_dictionary = {
    "key1": value1,
    "key2": value2,
    "key3": value3,
    "key4": value4
}

The **order** of the keys inside your dictionary does not matter

In [ ]:
# Lets make a dictionary with the same contents but different key order
my_dictionary_diff_order = {
    "key3": value3,
    "key2": value2,
    "key1": value1,
    "key4": value4
}

# Lets test if our dictionaries are the same
my_dictionary == my_dictionary_diff_order

Let's try having non **unique keys**

In [ ]:
# Lets create a dictionary with repeating keys
my_dictionary_rep_keys = {
    "key1": value1,
    "key1": value1,
    "key1": value1,
    "key4": value1
}

The **keys** must be **immutable data types**. **Mutable data types** include: lists, sets, and dictionaries (so don't use these as your keys)! However, **mutable** data types can be used as the values in your dictionary.

In [ ]:
# Lets create a dictionary using these guidlines
my_dictionary = {
    "key": [1, 2],
    42: "The answer",
    0: None,
    33.2: 22.3
}

Now that we know a bit about **dictionaries**, lets see what we can do with them. With dictionaries we can **create**, **query** (access), and **modify**. lets take a look at this!

**Creating** a dictionary

In [ ]:
d1 = {}
d2 = dict()
# d1 and d2 are now empty dictionaries

favorite_colors = {
    "asfg": "Blue",
    "among": "Blue",
    "paolopan": "yellow",
    "sg721": "green"
}
# favorite_colors is now a dictionary with some inital keys and values

In [ ]:
state_capitals = {"GA" : "Atlanta", "WA": "Olympia" }

phonebook = dict()
phonebook["Alice"] = "206-555-4455"
phonebook["Bob"] = "212-555-2211"

atomic_number = {}
atomic_number["H"] = 1
atomic_number["Fe"] = 26
atomic_number["Au"] = 79

**Accessing** a dictionary

In [ ]:
atomic_number = {"H": 1, "Fe": 26, "Au": 79}

# Lets print the values contained by the key "Au"
print(atomic_number["Au"])

# What about if we use a key that does not exist in our dictionary?
# print(atomic_number["B"])

# Lets check if the key "Au" is in our dictionary
print("Au" in atomic_number)

# Lets check if the value 26 is in our dictionary
print(26 in atomic_number)

# Lets print the keys of our dictionary
print(atomic_number.keys())
print(list(atomic_number.keys()))

# Lets print the values of our dictionary
print(atomic_number.values())
print(list(atomic_number.values()))

print(list(atomic_number.items()))

**Iterating** through a dictionary

In [ ]:
# We will use the atomic_number we had created above

# Print out all the keys: 
for element_name in atomic_number.keys():
    print(element_name)

# Another way to print out all the keys: 
for element_name in atomic_number:
    print(element_name)
    
# Print out all the values: 
for element_number in atomic_number.values():
    print(element_number)

# Print out the keys and the values
for (element_name, element_number) in atomic_number.items():
    print("name:", element_name, "number:", element_number)

**Modifying** a dictionary

In [ ]:
# Lets create a new dictionary mapping the species of the pet with the pet names!
pet_names = {
    "Ducks": ["Duckula", "Howard", "Daffy"],
    "Mice": ["Stuart", "Mickey", "Templeton"],
    "Horses": ["Secretariat", "Black Beauty"]
}

# Lets add to our dictionaries mapping
pet_names["Rabbits"] = ["Peter", "Energizer"]

# Now lets changing the mapping of our dictionary
pet_names["Horses"] = ["Misty"] #Change mapping

# Finally, lets remove mapping
del pet_names["Mice"]

Lets work through some **dictionary exercises**

In [ ]:
# What do you think this does?
squares = {1: 1, 2: 4, 3: 9, 4: 16}
print(squares[3] + squares[3])
print(squares[3 + 3])
print(squares[2] + squares[2])
print(squares[2 + 2])

In [ ]:
# How about converting a list to a dictionary?
# E.g. Given [5, 6, 7], produce {5: 25, 6: 36, 7: 49}

d = {}
for i in [5, 6, 7]:    # or range(5, 8)
    d[i] = i * i
    
k = {}
for i in d.keys():
     k[d[i]] = i

Aside: A **list** is (kind of) like a **dictionary**

In [ ]:
# Lists map integers using an index for each value
mylist = ['a', 'b', 'c']
mylist[3] = 'c'  # error!

Lets stop and think...

When is a list **more convenient** to use then a dictionary?

When is a list **less convenient** to use then a dictionary?

Lets dive into the specifics to **keys** for dictionaries

Not every value is allowed to be a **key** in a **dictionary**

Dictionaries hold key: value pairs

as we mentioned earlier, the keys of a dictionary must be **immutable**, however the values in a dictionary can be **anything**.

**Mutable** and **immutable** data types

**Immutable datatypes:**
int, float, boolean, string, function, tuple, frozenset

**Mutable datatypes:**
list, dictionary, set

### Reading data from a file 

- We'll usually work with data stored in the CSV format. CSV stands for "comma-separated values."

- We can read in a CSV using `pd.read_csv(...)`. Replace the `...` with a path to the CSV file relative to your notebook; if the file is in the same folder as your notebook, this is just the name of the file.

In [10]:
# Our CSV file is stored not in the same folder as our notebook,
# but two folders up, inside data/raw. Each row is one member of the
# House in one Congress (1947 to 2012).
congress = pd.read_csv('../../data/raw/congress.csv')
congress

       congress  district    state       party         name  dwnom1  dwnom2
0            80         0      USA    Democrat       TRUMAN  -0.276   0.016
1            80         1  ALABAMA    Democrat   BOYKIN  F.  -0.026   0.796
2            80         2  ALABAMA    Democrat    GRANT  G.  -0.042   0.999
3            80         3  ALABAMA    Democrat  ANDREWS  G.  -0.008   1.005
4            80         4  ALABAMA    Democrat    HOBBS  S.  -0.082   1.066
...         ...       ...      ...         ...          ...     ...     ...
14547       112         5  WISCONS  Republican     SENSENBR   1.200  -0.438
14548       112         6  WISCONS  Republican        PETRI   0.776  -0.003
14549       112         7  WISCONS  Republican        DUFFY   0.781  -0.270
14550       112         8  WISCONS  Republican       RIBBLE   0.886  -0.193
14551       112         1  WYOMING  Republican       LUMMIS   0.932  -0.211

[14552 rows x 7 columns]

- 14,552 rows and 7 columns. `'dwnom1'` is an ideology score: negative is liberal, positive is conservative. We return to this table next lecture.
- For today's examples we use a smaller table that we built from the *Federalist* essays: one row per essay.

In [11]:
federalist = pd.read_csv('../../data/derived/federalist_counts.csv')
federalist

    essay    author  words  by  from   to  upon  whilst  while
0       1  Hamilton   1588  14    11   70     6       0      0
1       2       Jay   1663  10     4   52     1       0      1
2       3       Jay   1439  18    15   55     0       0      0
3       4       Jay   1636  14     8   50     0       0      0
4       5       Jay   1337  10    11   44     0       0      0
..    ...       ...    ...  ..   ...  ...   ...     ...    ...
80     81  Hamilton   3790  32    20  156    13       1      2
81     82  Hamilton   1534   4    14   82     4       0      0
82     83  Hamilton   5716  79    22  213    20       0      4
83     84  Hamilton   3921  28    20  130    11       0      1
84     85  Hamilton   2660  11     9  113    12       0      0

[85 rows x 9 columns]

### About the data 📜

Most of the data is self-explanatory, but there are a few things to note:

- One row is one essay. `'author'` records what historians established: Hamilton, Madison, Jay, or `'Disputed or joint'`.

- `'words'` is the number of words in the essay after lowercasing and dropping punctuation.

- `'by'`, `'from'`, `'to'`, `'upon'`, `'whilst'`, and `'while'` count how many times each word appears as a whole word.

### Structure of a DataFrame

- DataFrames have *columns* and *rows*.
    - Think of each column as an array. Columns contain data of the same type.
- Each column has a label, e.g. `'author'` and `'words'`.
    - Column labels are stored as strings.
- Each row has a label too – these are shown in bold at the start of the row.
    - Right now, the row labels are 0, 1, 2, and so on.
    - Together, the row labels are called the _index_. The index is **not** a column!

In [12]:
# This DataFrame has 85 rows and 9 columns.
federalist

    essay    author  words  by  from   to  upon  whilst  while
0       1  Hamilton   1588  14    11   70     6       0      0
1       2       Jay   1663  10     4   52     1       0      1
2       3       Jay   1439  18    15   55     0       0      0
3       4       Jay   1636  14     8   50     0       0      0
4       5       Jay   1337  10    11   44     0       0      0
..    ...       ...    ...  ..   ...  ...   ...     ...    ...
80     81  Hamilton   3790  32    20  156    13       1      2
81     82  Hamilton   1534   4    14   82     4       0      0
82     83  Hamilton   5716  79    22  213    20       0      4
83     84  Hamilton   3921  28    20  130    11       0      1
84     85  Hamilton   2660  11     9  113    12       0      0

[85 rows x 9 columns]

## Example 1: How often does each essay use "upon"?

**Key concepts**: Accessing columns, performing calculations with them, and adding new columns.

### Finding a rate

**Question**: How many times per 1,000 words does each essay use the word "upon"?

A raw count is unfair: essay 83 is six times longer than essay 13, so it has six times the chances. A rate fixes that.

In [13]:
federalist

    essay    author  words  by  from   to  upon  whilst  while
0       1  Hamilton   1588  14    11   70     6       0      0
1       2       Jay   1663  10     4   52     1       0      1
2       3       Jay   1439  18    15   55     0       0      0
3       4       Jay   1636  14     8   50     0       0      0
4       5       Jay   1337  10    11   44     0       0      0
..    ...       ...    ...  ..   ...  ...   ...     ...    ...
80     81  Hamilton   3790  32    20  156    13       1      2
81     82  Hamilton   1534   4    14   82     4       0      0
82     83  Hamilton   5716  79    22  213    20       0      4
83     84  Hamilton   3921  28    20  130    11       0      1
84     85  Hamilton   2660  11     9  113    12       0      0

[85 rows x 9 columns]

- We have, separately, the count of "upon" and the total number of words in each essay.

- Steps:
    - Get the `'upon'` column.
    - Get the `'words'` column.
    - Divide these columns element-wise, then multiply by 1,000.
    - Add a new column to the DataFrame with these results.

#### Step 1 – Getting the `'upon'` column

- We can get a column from a DataFrame using `.get(column_name)`.
- Column names are case sensitive!
- Column names are strings, so we need to use quotes.
- The result looks like a 1-column DataFrame, but is actually a *Series*.

In [14]:
federalist

    essay    author  words  by  from   to  upon  whilst  while
0       1  Hamilton   1588  14    11   70     6       0      0
1       2       Jay   1663  10     4   52     1       0      1
2       3       Jay   1439  18    15   55     0       0      0
3       4       Jay   1636  14     8   50     0       0      0
4       5       Jay   1337  10    11   44     0       0      0
..    ...       ...    ...  ..   ...  ...   ...     ...    ...
80     81  Hamilton   3790  32    20  156    13       1      2
81     82  Hamilton   1534   4    14   82     4       0      0
82     83  Hamilton   5716  79    22  213    20       0      4
83     84  Hamilton   3921  28    20  130    11       0      1
84     85  Hamilton   2660  11     9  113    12       0      0

[85 rows x 9 columns]

In [15]:
federalist.get('upon')

0      6
1      1
2      0
3      0
4      0
      ..
80    13
81     4
82    20
83    11
84    12
Name: upon, Length: 85, dtype: int64

### Digression: Series

- A *Series* is like an array, but with an index.
- In particular, Series support arithmetic, just like arrays.

In [16]:
federalist.get('upon')

0      6
1      1
2      0
3      0
4      0
      ..
80    13
81     4
82    20
83    11
84    12
Name: upon, Length: 85, dtype: int64

In [17]:
type(federalist.get('upon'))

pandas.core.series.Series

#### Steps 2 and 3 – Getting the `'words'` column and dividing element-wise

In [18]:
federalist.get('words')

0     1588
1     1663
2     1439
3     1636
4     1337
      ...
80    3790
81    1534
82    5716
83    3921
84    2660
Name: words, Length: 85, dtype: int64

- Just like with arrays, we can perform arithmetic operations with two Series, as long as they have the same length and same index. 
- Operations happen element-wise (by matching up corresponding index values), and the result is also a Series.

In [19]:
federalist.get('upon') / federalist.get('words') * 1000

0     3.778338
1     0.601323
2     0.000000
3     0.000000
4     0.000000
        ...
80    3.430079
81    2.607562
82    3.498950
83    2.805407
84    4.511278
Length: 85, dtype: float64

#### Step 4 – Adding the rates to the DataFrame as a new column

- Use `.assign(name_of_column=data_in_series)` to assign a Series (or array, or list) to a DataFrame.
- Don't put quotes around `name_of_column`.
- This creates a new DataFrame, which we must save to a variable if we want to keep using it.

In [20]:
federalist.assign(
    upon_rate=federalist.get('upon') / federalist.get('words') * 1000
)

    essay    author  words  by  from   to  upon  whilst  while  upon_rate
0       1  Hamilton   1588  14    11   70     6       0      0   3.778338
1       2       Jay   1663  10     4   52     1       0      1   0.601323
2       3       Jay   1439  18    15   55     0       0      0   0.000000
3       4       Jay   1636  14     8   50     0       0      0   0.000000
4       5       Jay   1337  10    11   44     0       0      0   0.000000
..    ...       ...    ...  ..   ...  ...   ...     ...    ...        ...
80     81  Hamilton   3790  32    20  156    13       1      2   3.430079
81     82  Hamilton   1534   4    14   82     4       0      0   2.607562
82     83  Hamilton   5716  79    22  213    20       0      4   3.498950
83     84  Hamilton   3921  28    20  130    11       0      1   2.805407
84     85  Hamilton   2660  11     9  113    12       0      0   4.511278

[85 rows x 10 columns]

In [21]:
federalist

    essay    author  words  by  from   to  upon  whilst  while
0       1  Hamilton   1588  14    11   70     6       0      0
1       2       Jay   1663  10     4   52     1       0      1
2       3       Jay   1439  18    15   55     0       0      0
3       4       Jay   1636  14     8   50     0       0      0
4       5       Jay   1337  10    11   44     0       0      0
..    ...       ...    ...  ..   ...  ...   ...     ...    ...
80     81  Hamilton   3790  32    20  156    13       1      2
81     82  Hamilton   1534   4    14   82     4       0      0
82     83  Hamilton   5716  79    22  213    20       0      4
83     84  Hamilton   3921  28    20  130    11       0      1
84     85  Hamilton   2660  11     9  113    12       0      0

[85 rows x 9 columns]

In [22]:
federalist = federalist.assign(
    upon_rate=federalist.get('upon') / federalist.get('words') * 1000
)
federalist

    essay    author  words  by  from   to  upon  whilst  while  upon_rate
0       1  Hamilton   1588  14    11   70     6       0      0   3.778338
1       2       Jay   1663  10     4   52     1       0      1   0.601323
2       3       Jay   1439  18    15   55     0       0      0   0.000000
3       4       Jay   1636  14     8   50     0       0      0   0.000000
4       5       Jay   1337  10    11   44     0       0      0   0.000000
..    ...       ...    ...  ..   ...  ...   ...     ...    ...        ...
80     81  Hamilton   3790  32    20  156    13       1      2   3.430079
81     82  Hamilton   1534   4    14   82     4       0      0   2.607562
82     83  Hamilton   5716  79    22  213    20       0      4   3.498950
83     84  Hamilton   3921  28    20  130    11       0      1   2.805407
84     85  Hamilton   2660  11     9  113    12       0      0   4.511278

[85 rows x 10 columns]

## Example 2: Exploring the rate
**Key concept**: Computing statistics of columns using Series methods.

### Questions

- What is the highest "upon" rate of any one essay? 
- What is the average "upon" rate across all essays?

Series, like arrays, have helpful methods, including `.min()`, `.max()`, and `.mean()`.

In [23]:
federalist.get('upon_rate').max()

7.514450867052023

What essay does this correspond to? We'll see how to find out shortly!

Other statistics:

In [24]:
federalist.get('upon_rate').min()

0.0

In [25]:
federalist.get('upon_rate').mean()

2.0454851729604253

In [26]:
federalist.get('upon_rate').median()

1.959503592423253

In [27]:
# Lots of information at once!
federalist.get('upon_rate').describe()

count    85.000000
mean      2.045485
std       1.886691
min       0.000000
25%       0.000000
50%       1.959504
75%       3.498950
max       7.514451
Name: upon_rate, dtype: float64

## Example 3: *Which* essay uses "upon" the most?

**Key concepts**: Sorting. Accessing using integer positions.

#### Step 1  – Sorting the DataFrame

- Use the `.sort_values(by=column_name)` method to sort.
    - The `by=` can be omitted, but helps with readability.
- Like most DataFrame methods, this returns a new DataFrame.

In [28]:
federalist.sort_values(by='upon_rate')

,essay,author,words,by,from,to,upon,whilst,while,upon_rate
42,43,Madison,3427,47,6,111,0,1,0,0.000000
38,39,Madison,2606,33,23,90,0,0,0,0.000000
54,55,Disputed or joint,2044,14,12,77,0,0,0,0.000000
55,56,Disputed or joint,1565,10,9,38,0,1,0,0.000000
48,49,Disputed or joint,1646,15,5,57,0,1,0,0.000000
...,...,...,...,...,...,...,...,...,...,...
76,77,Hamilton,1970,16,13,71,10,0,1,5.076142
32,33,Hamilton,1683,14,9,66,9,0,0,5.347594
72,73,Hamilton,2347,27,13,82,13,0,0,5.538986
29,30,Hamilton,1965,14,8,75,13,0,0,6.615776
30,31,Hamilton,1730,9,10,81,13,0,0,7.514451

This sorts, but in ascending order (small to large). The opposite would be nice!

#### Step 1 – Sorting the DataFrame in *descending* order

- Use `.sort_values(by=column_name, ascending=False)` to sort in *descending* order.
- `ascending` is an optional argument. If omitted, it will be set to `True` by default.
    - This is an example of a *keyword argument*, or a *named argument*.
    - If we want to specify the sorting order, we **must** use the keyword `ascending=`.

In [29]:
ordered_essays = federalist.sort_values(by='upon_rate', ascending=False)
ordered_essays

,essay,author,words,by,from,to,upon,whilst,while,upon_rate
30,31,Hamilton,1730,9,10,81,13,0,0,7.514451
29,30,Hamilton,1965,14,8,75,13,0,0,6.615776
72,73,Hamilton,2347,27,13,82,13,0,0,5.538986
32,33,Hamilton,1683,14,9,66,9,0,0,5.347594
76,77,Hamilton,1970,16,13,71,10,0,1,5.076142
...,...,...,...,...,...,...,...,...,...,...
55,56,Disputed or joint,1565,10,9,38,0,1,0,0.000000
56,57,Disputed or joint,2206,25,11,73,0,3,0,0.000000
57,58,Madison,2080,22,10,60,0,0,0,0.000000
61,62,Disputed or joint,2387,28,21,81,0,0,0,0.000000
42,43,Madison,3427,47,6,111,0,1,0,0.000000

In [30]:
# We must specify the role of False by using ascending=, 
# otherwise Python does not know how to interpret this.
federalist.sort_values(by='upon_rate', False)

SyntaxError: positional argument follows keyword argument (3297039976.py, line 3)

#### Step 2 – Extracting the essay number and author

- We saw which essay tops the list, but how do we extract that information using code?
- First, grab an entire column as a Series.
- Navigate to a particular entry of the Series using `.iloc[integer_position]`.
    - `iloc` stands for "integer location" and is used to count the rows, starting at 0.

In [31]:
ordered_essays

,essay,author,words,by,from,to,upon,whilst,while,upon_rate
30,31,Hamilton,1730,9,10,81,13,0,0,7.514451
29,30,Hamilton,1965,14,8,75,13,0,0,6.615776
72,73,Hamilton,2347,27,13,82,13,0,0,5.538986
32,33,Hamilton,1683,14,9,66,9,0,0,5.347594
76,77,Hamilton,1970,16,13,71,10,0,1,5.076142
...,...,...,...,...,...,...,...,...,...,...
55,56,Disputed or joint,1565,10,9,38,0,1,0,0.000000
56,57,Disputed or joint,2206,25,11,73,0,3,0,0.000000
57,58,Madison,2080,22,10,60,0,0,0,0.000000
61,62,Disputed or joint,2387,28,21,81,0,0,0,0.000000
42,43,Madison,3427,47,6,111,0,1,0,0.000000

In [32]:
ordered_essays.get('essay')

30    31
29    30
72    73
32    33
76    77
      ..
55    56
56    57
57    58
61    62
42    43
Name: essay, Length: 85, dtype: int64

In [33]:
# We want the first entry of the Series, which is at "integer location" 0.
ordered_essays.get('essay').iloc[0]

31

In [34]:
# And its author.
ordered_essays.get('author').iloc[0]

'Hamilton'

- The row label that goes with the top essay is its essay number minus 1, because our original data was in essay order. But we **don't use the row label** when accessing with `iloc`; we use the integer position counting from the top.

- If we try to use that row label with `iloc`, we get a different essay, the one at that position in the *sorted* table.

In [35]:
# Row label 30 is not position 30 in the sorted table.
ordered_essays.get('essay').iloc[30]

84

## Example 4: What is the "upon" rate of essay 10?

**Key concepts**: Setting the index. Accessing using row labels.

### The rate of essay 10

Essay 10 is Madison's most famous essay. We know how to get the `'upon_rate'` of all essays. How do we find the one that corresponds to essay 10?

In [36]:
federalist

    essay    author  words  by  from   to  upon  whilst  while  upon_rate
0       1  Hamilton   1588  14    11   70     6       0      0   3.778338
1       2       Jay   1663  10     4   52     1       0      1   0.601323
2       3       Jay   1439  18    15   55     0       0      0   0.000000
3       4       Jay   1636  14     8   50     0       0      0   0.000000
4       5       Jay   1337  10    11   44     0       0      0   0.000000
..    ...       ...    ...  ..   ...  ...   ...     ...    ...        ...
80     81  Hamilton   3790  32    20  156    13       1      2   3.430079
81     82  Hamilton   1534   4    14   82     4       0      0   2.607562
82     83  Hamilton   5716  79    22  213    20       0      4   3.498950
83     84  Hamilton   3921  28    20  130    11       0      1   2.805407
84     85  Hamilton   2660  11     9  113    12       0      0   4.511278

[85 rows x 10 columns]

In [37]:
# Which one is essay 10?
federalist.get('upon_rate')

0     3.778338
1     0.601323
2     0.000000
3     0.000000
4     0.000000
        ...
80    3.430079
81    2.607562
82    3.498950
83    2.805407
84    4.511278
Name: upon_rate, Length: 85, dtype: float64

### Utilizing the index

- When we load in a DataFrame from a CSV, columns have meaningful names, but rows do not.

In [38]:
pd.read_csv('../../data/derived/federalist_counts.csv')

    essay    author  words  by  from   to  upon  whilst  while
0       1  Hamilton   1588  14    11   70     6       0      0
1       2       Jay   1663  10     4   52     1       0      1
2       3       Jay   1439  18    15   55     0       0      0
3       4       Jay   1636  14     8   50     0       0      0
4       5       Jay   1337  10    11   44     0       0      0
..    ...       ...    ...  ..   ...  ...   ...     ...    ...
80     81  Hamilton   3790  32    20  156    13       1      2
81     82  Hamilton   1534   4    14   82     4       0      0
82     83  Hamilton   5716  79    22  213    20       0      4
83     84  Hamilton   3921  28    20  130    11       0      1
84     85  Hamilton   2660  11     9  113    12       0      0

[85 rows x 9 columns]

- The row labels (or the *index*) are how we refer to specific rows. Instead of using positions, let's refer to these rows by the essay numbers they correspond to.

- This way, we can easily identify, for example, which row corresponds to essay 10.

### Setting the index

- To change the index, use `.set_index(column_name)`.
- Row labels should be unique identifiers.
    - Each row should have a different, descriptive name that corresponds to the contents of that row's data. Every essay has its own number, so `'essay'` works. `'author'` would not: many essays share an author.

In [39]:
federalist

    essay    author  words  by  from   to  upon  whilst  while  upon_rate
0       1  Hamilton   1588  14    11   70     6       0      0   3.778338
1       2       Jay   1663  10     4   52     1       0      1   0.601323
2       3       Jay   1439  18    15   55     0       0      0   0.000000
3       4       Jay   1636  14     8   50     0       0      0   0.000000
4       5       Jay   1337  10    11   44     0       0      0   0.000000
..    ...       ...    ...  ..   ...  ...   ...     ...    ...        ...
80     81  Hamilton   3790  32    20  156    13       1      2   3.430079
81     82  Hamilton   1534   4    14   82     4       0      0   2.607562
82     83  Hamilton   5716  79    22  213    20       0      4   3.498950
83     84  Hamilton   3921  28    20  130    11       0      1   2.805407
84     85  Hamilton   2660  11     9  113    12       0      0   4.511278

[85 rows x 10 columns]

In [40]:
federalist.set_index('essay')

         author  words  by  from   to  upon  whilst  while  upon_rate
essay
1      Hamilton   1588  14    11   70     6       0      0   3.778338
2           Jay   1663  10     4   52     1       0      1   0.601323
3           Jay   1439  18    15   55     0       0      0   0.000000
4           Jay   1636  14     8   50     0       0      0   0.000000
5           Jay   1337  10    11   44     0       0      0   0.000000
...         ...    ...  ..   ...  ...   ...     ...    ...        ...
81     Hamilton   3790  32    20  156    13       1      2   3.430079
82     Hamilton   1534   4    14   82     4       0      0   2.607562
83     Hamilton   5716  79    22  213    20       0      4   3.498950
84     Hamilton   3921  28    20  130    11       0      1   2.805407
85     Hamilton   2660  11     9  113    12       0      0   4.511278

[85 rows x 9 columns]

- Now there is one fewer column. When you set the index, a column becomes the index, and the old index disappears.

- 🚨 Like most DataFrame methods, `.set_index` returns a new DataFrame; it does not modify the original DataFrame.

In [41]:
federalist

    essay    author  words  by  from   to  upon  whilst  while  upon_rate
0       1  Hamilton   1588  14    11   70     6       0      0   3.778338
1       2       Jay   1663  10     4   52     1       0      1   0.601323
2       3       Jay   1439  18    15   55     0       0      0   0.000000
3       4       Jay   1636  14     8   50     0       0      0   0.000000
4       5       Jay   1337  10    11   44     0       0      0   0.000000
..    ...       ...    ...  ..   ...  ...   ...     ...    ...        ...
80     81  Hamilton   3790  32    20  156    13       1      2   3.430079
81     82  Hamilton   1534   4    14   82     4       0      0   2.607562
82     83  Hamilton   5716  79    22  213    20       0      4   3.498950
83     84  Hamilton   3921  28    20  130    11       0      1   2.805407
84     85  Hamilton   2660  11     9  113    12       0      0   4.511278

[85 rows x 10 columns]

In [42]:
federalist = federalist.set_index('essay')
federalist

         author  words  by  from   to  upon  whilst  while  upon_rate
essay
1      Hamilton   1588  14    11   70     6       0      0   3.778338
2           Jay   1663  10     4   52     1       0      1   0.601323
3           Jay   1439  18    15   55     0       0      0   0.000000
4           Jay   1636  14     8   50     0       0      0   0.000000
5           Jay   1337  10    11   44     0       0      0   0.000000
...         ...    ...  ..   ...  ...   ...     ...    ...        ...
81     Hamilton   3790  32    20  156    13       1      2   3.430079
82     Hamilton   1534   4    14   82     4       0      0   2.607562
83     Hamilton   5716  79    22  213    20       0      4   3.498950
84     Hamilton   3921  28    20  130    11       0      1   2.805407
85     Hamilton   2660  11     9  113    12       0      0   4.511278

[85 rows x 9 columns]

In [43]:
# Which one is essay 10? The one whose row label is 10!
federalist.get('upon_rate')

essay
1     3.778338
2     0.601323
3     0.000000
4     0.000000
5     0.000000
        ...
81    3.430079
82    2.607562
83    3.498950
84    2.805407
85    4.511278
Name: upon_rate, Length: 85, dtype: float64

### Accessing using the row label

To pull out one particular entry of a DataFrame corresponding to a row and column with certain labels:
1. Use `.get(column_name)` to extract the entire column as a Series.
2. Use `.loc[]` to access the element of a Series with a particular row label.

In this class, we'll always first access a column, then a row (but row, then column is also possible).

In [44]:
federalist.get('upon_rate')

essay
1     3.778338
2     0.601323
3     0.000000
4     0.000000
5     0.000000
        ...
81    3.430079
82    2.607562
83    3.498950
84    2.805407
85    4.511278
Name: upon_rate, Length: 85, dtype: float64

In [45]:
federalist.get('upon_rate').loc[10]

0.0

### Summary: Accessing elements of a DataFrame

- First, `.get` the appropriate column as a Series.
- Then, use one of two ways to access an element of a Series:
    - `.iloc[]` uses the integer position.
    - `.loc[]` uses the row label.
    - Each is best for different scenarios.

In [46]:
federalist.get('upon_rate')

essay
1     3.778338
2     0.601323
3     0.000000
4     0.000000
5     0.000000
        ...
81    3.430079
82    2.607562
83    3.498950
84    2.805407
85    4.511278
Name: upon_rate, Length: 85, dtype: float64

In [47]:
# Position 9 is the tenth row: essay 10.
federalist.get('upon_rate').iloc[9]

0.0

In [48]:
# Label 10 is essay 10. Same value, two ways to ask.
federalist.get('upon_rate').loc[10]

0.0

### Note

- Sometimes the integer position and row label are the same.
- This happens by default with `pd.read_csv`.

In [49]:
pd.read_csv('../../data/derived/federalist_counts.csv')

    essay    author  words  by  from   to  upon  whilst  while
0       1  Hamilton   1588  14    11   70     6       0      0
1       2       Jay   1663  10     4   52     1       0      1
2       3       Jay   1439  18    15   55     0       0      0
3       4       Jay   1636  14     8   50     0       0      0
4       5       Jay   1337  10    11   44     0       0      0
..    ...       ...    ...  ..   ...  ...   ...     ...    ...
80     81  Hamilton   3790  32    20  156    13       1      2
81     82  Hamilton   1534   4    14   82     4       0      0
82     83  Hamilton   5716  79    22  213    20       0      4
83     84  Hamilton   3921  28    20  130    11       0      1
84     85  Hamilton   2660  11     9  113    12       0      0

[85 rows x 9 columns]

In [50]:
pd.read_csv('../../data/derived/federalist_counts.csv').get('author').loc[35]

'Hamilton'

In [51]:
pd.read_csv('../../data/derived/federalist_counts.csv').get('author').iloc[35]

'Hamilton'